
- name: Install and configure Nginx
  hosts: NGINX
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      command: nginx
