
- name: Backup configuration files
  hosts: NGINX
  become: yes

  tasks:

    - name: Create backup directory
      file:
        path: /tmp/backup
        state: directory
        mode: '0755'

    - name: Backup nginx config
      copy:
        src: /etc/nginx/nginx.conf
        dest: /tmp/backup/nginx.conf.bak
        remote_src: yes
